"""cambie el nomnbre tabla de producto_model a productos

Revision ID: 40f1f6c00420
Revises: 3dc91395db20
Create Date: 2024-11-29 20:32:31.587163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f1f6c00420'
down_revision = '3dc91395db20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # https://alembic.sqlalchemy.org/en/latest/ops.html#alembic.operations.Operations.rename_table
    op.rename_table('producto_model', 'productos')
    # op.drop_table('producto_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('productos', 'producto_model')
    # op.drop_table('productos')
    # ### end Alembic commands ###
