"""creacion de tablas

Revision ID: 686cff979491
Revises: 
Create Date: 2024-12-11 22:26:37.258224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686cff979491'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('libro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.TIMESTAMP(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('libro')
    op.drop_table('categorias')
    # ### end Alembic commands ###


def upgrade_mysql():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('apellido', sa.Text(), nullable=True),
    sa.Column('correo', sa.String(100), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('tipo_usuario', sa.Enum('ADMIN', 'CLIENTE', 'EMPLEADO', name='tipousuario'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    # ### end Alembic commands ###


def downgrade_mysql():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###

