from .categoria import CategoriaSerializer
from .usuario_serializer import RegistroSerializer
from .usuario_serializer import LoginSerializer, RegistroSerializer, ActualizarUsuarioSerializer, OlvidePasswordSerializer
from .libro_serializer import LibroSerializer
